# Alacritty pywal16 color scheme

[colors.primary]
background = '{background}'
foreground = '{foreground}'

[colors.cursor]
text = '{background}'
cursor = '{foreground}'

[colors.vi_mode_cursor]
text = '{background}'
cursor = '{foreground}'

[colors.search.matches]
foreground = '{background}'
background = '{foreground}'

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = '{color8}'
background = '{foreground}'

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = '{color0}'
red = '{color1}'
green = '{color2}'
yellow = '{color3}'
blue = '{color4}'
magenta = '{color5}'
cyan = '{color6}'
white = '{color7}'

[colors.bright]
black = '{color8}'
red = '{color9}'
green = '{color10}'
yellow = '{color11}'
blue = '{color12}'
magenta = '{color13}'
cyan = '{color14}'
white = '{color15}'

[colors.dim]
black = '{foreground}'
red = '{color1}'
green = '{color5}'
yellow = '{color3}'
blue = '{color4}'
magenta = '{color2}'
cyan = '{color6}'
white = '{color8}'
